# Day 1: Pandas Essentials
**Phase 1 — Python, Data, PyTorch** | April 21, 2026

Today you'll learn the core building blocks of pandas: how to load data, inspect it, select rows and columns, filter, and summarize with groupby.

By the end of this notebook, you should be able to:
- Load a CSV into a DataFrame
- Tell the difference between a Series and a DataFrame
- Filter rows with boolean indexing
- Select data with `loc` and `iloc`
- Summarize data with `groupby`

In [2]:
import pandas as pd
import numpy as np

print(f"pandas version: {pd.__version__}")
print(f"numpy version: {np.__version__}")

pandas version: 3.0.2
numpy version: 2.4.4

---
## 1. Creating Our Sample Data

We'll build a small dataset so every cell in this notebook runs without external files.

In [3]:
# Create a sample customer dataset
df = pd.DataFrame({
    "name":     ["Ali", "Bea", "Can", "Deniz", "Elif", "Fatma", "Gokhan", "Hana", "Ibrahim", "Jale"],
    "city":     ["Berlin", "Istanbul", "Berlin", "Istanbul", "Ankara", "Berlin", "Ankara", "Istanbul", "Berlin", "Ankara"],
    "age":      [28, 34, 22, 31, 45, 29, 38, 26, 41, 33],
    "spending": [120, 450, 80, 620, 310, 200, 530, 90, 400, 275],
    "gender":   ["M", "F", "M", "M", "F", "F", "M", "F", "M", "F"],
    "email":    ["ali@x.com", None, "can@x.com", "deniz@x.com", None, "fatma@x.com", "gokhan@x.com", None, "ibrahim@x.com", "jale@x.com"]
})

df

      name      city  age  spending gender          email
0      Ali    Berlin   28       120      M      ali@x.com
1      Bea  Istanbul   34       450      F            NaN
2      Can    Berlin   22        80      M      can@x.com
3    Deniz  Istanbul   31       620      M    deniz@x.com
4     Elif    Ankara   45       310      F            NaN
5    Fatma    Berlin   29       200      F    fatma@x.com
6   Gokhan    Ankara   38       530      M   gokhan@x.com
7     Hana  Istanbul   26        90      F            NaN
8  Ibrahim    Berlin   41       400      M  ibrahim@x.com
9     Jale    Ankara   33       275      F     jale@x.com

---
## 2. Series vs DataFrame

A **DataFrame** is the whole table. A **Series** is a single column. This distinction matters because they have different methods and behaviors.

In [4]:
# Single brackets -> Series
age_series = df["age"]
print(type(age_series))
print(age_series)
print()

# Double brackets -> DataFrame (with one column)
age_df = df[["age"]]
print(type(age_df))
print(age_df)

<class 'pandas.Series'>
0    28
1    34
2    22
3    31
4    45
5    29
6    38
7    26
8    41
9    33
Name: age, dtype: int64

<class 'pandas.DataFrame'>
   age
0   28
1   34
2   22
3   31
4   45
5   29
6   38
7   26
8   41
9   33

In [5]:
# A Series has an index and values
print("Index:", age_series.index.tolist())
print("Values:", age_series.values)
print("Name:", age_series.name)
print("Dtype:", age_series.dtype)

Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Values: [28 34 22 31 45 29 38 26 41 33]
Name: age
Dtype: int64

In [6]:
# Series has methods that DataFrames don't (and vice versa)
# .str accessor only works on a Series of strings
print(df["name"].str.upper())
print()

# You can do math directly on a numeric Series
print("Mean age:", df["age"].mean())
print("Total spending:", df["spending"].sum())

0        ALI
1        BEA
2        CAN
3      DENIZ
4       ELIF
5      FATMA
6     GOKHAN
7       HANA
8    IBRAHIM
9       JALE
Name: name, dtype: str

Mean age: 32.7
Total spending: 3075

---
## 3. Inspecting Your Data (read_csv style)

In real life you'd use `pd.read_csv("file.csv")`. Here we already have `df`, but the inspection tools are the same. These are the first things you run after loading any dataset.

In [7]:
# .head() shows the first N rows (default 5)
df.head(3)

  name      city  age  spending gender      email
0  Ali    Berlin   28       120      M  ali@x.com
1  Bea  Istanbul   34       450      F        NaN
2  Can    Berlin   22        80      M  can@x.com

In [8]:
# .shape gives (rows, columns) as a tuple
print("Shape:", df.shape)
print(f"  -> {df.shape[0]} rows, {df.shape[1]} columns")

Shape: (10, 6)
  -> 10 rows, 6 columns

In [9]:
# .dtypes shows the data type of each column
# "object" usually means string in pandas
df.dtypes

name          str
city          str
age         int64
spending    int64
gender        str
email         str
dtype: object

In [10]:
# .info() is the all-in-one summary: dtypes, non-null counts, memory
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      10 non-null     str
 1   city      10 non-null     str
 2   age       10 non-null     int64
 3   spending  10 non-null     int64
 4   gender    10 non-null     str
 5   email     7 non-null      str
dtypes: int64(2), str(4)
memory usage: 809.0 bytes

In [14]:
# .describe() gives summary statistics for numeric columns
# count, mean, std, min, 25%, 50%, 75%, max

# count: Number of non-missing values in the column.
# mean: Average value of the column.
# std: Standard deviation, which shows how spread out the values are.
# min: Smallest value in the column.
# 25%: First quartile, meaning 25% of values are at or below this number.
# 50%: Median, meaning the middle value when the data is sorted.
# 75%: Third quartile, meaning 75% of values are at or below this number.
# max: Largest value in the column.

df.describe()

             age    spending
count  10.000000   10.000000
mean   32.700000  307.500000
std     7.056124  189.403303
min    22.000000   80.000000
25%    28.250000  140.000000
50%    32.000000  292.500000
75%    37.000000  437.500000
max    45.000000  620.000000

In [15]:
# .columns lists all column names
# .index shows the row labels
print("Columns:", df.columns.tolist())
print("Index:", df.index.tolist())
print("Number of unique cities:", df["city"].nunique())
print("Unique cities:", df["city"].unique())

Columns: ['name', 'city', 'age', 'spending', 'gender', 'email']
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Number of unique cities: 3
Unique cities: <ArrowStringArray>
['Berlin', 'Istanbul', 'Ankara']
Length: 3, dtype: str

---
## 4. read_csv in Detail

Even though we built our data manually, you need to know `read_csv` well. Let's save our DataFrame to CSV and read it back with different options.

In [16]:
# Save to CSV first
df.to_csv("sample_customers.csv", index=False)

# Basic read
df_loaded = pd.read_csv("sample_customers.csv")
df_loaded.head(3)

  name      city  age  spending gender      email
0  Ali    Berlin   28       120      M  ali@x.com
1  Bea  Istanbul   34       450      F        NaN
2  Can    Berlin   22        80      M  can@x.com

In [22]:
# Useful read_csv parameters:

# 1. Force specific dtypes (prevents zip codes like "00123" from becoming 123)
df_typed = pd.read_csv("sample_customers.csv", dtype={"age": float, "name": str})
print("age dtype:", df_typed["age"].dtype)  # float64 instead of int64
print()

# 2. Read only specific columns
df_small = pd.read_csv("sample_customers.csv", usecols=["name", "city", "spending"])
print(df_small.columns.tolist())
print()

# 3. Read only first N rows (great for huge files)
df_peek = pd.read_csv("sample_customers.csv", nrows=3)
print(f"Only {len(df_peek)} rows loaded")
print()
print(df_peek)

age dtype: float64

['name', 'city', 'spending']

Only 3 rows loaded

  name      city  age  spending gender      email
0  Ali    Berlin   28       120      M  ali@x.com
1  Bea  Istanbul   34       450      F        NaN
2  Can    Berlin   22        80      M  can@x.com

In [23]:
# 4. Handle different separators (tab, semicolon, pipe, etc.)
df.to_csv("sample_tab.tsv", index=False, sep="\t")
df_tab = pd.read_csv("sample_tab.tsv", sep="\t")
print("Tab-separated loaded OK:", df_tab.shape)

# 5. Set a column as the index while reading
df_indexed = pd.read_csv("sample_customers.csv", index_col="name")
print("\nWith name as index:")
print(df_indexed.head(3))

Tab-separated loaded OK: (10, 6)

With name as index:
          city  age  spending gender      email
name
Ali     Berlin   28       120      M  ali@x.com
Bea   Istanbul   34       450      F        NaN
Can     Berlin   22        80      M  can@x.com

---
## 5. Filtering with Boolean Indexing

This is the most common way to select rows. You write a condition, and pandas returns only the rows where it's True.

In [24]:
# Step 1: The condition creates a boolean Series (True/False for each row)
mask = df["age"] > 30
print(mask)
print(f"\nType: {type(mask)}")

0    False
1     True
2    False
3     True
4     True
5    False
6     True
7    False
8     True
9     True
Name: age, dtype: bool

Type: <class 'pandas.Series'>

In [26]:
# Step 2: Pass that mask into the brackets to filter
older_than_30 = df[df["age"] > 30]
print(f"People older than 30: {len(older_than_30)}")
older_than_30

People older than 30: 6

      name      city  age  spending gender          email
1      Bea  Istanbul   34       450      F            NaN
3    Deniz  Istanbul   31       620      M    deniz@x.com
4     Elif    Ankara   45       310      F            NaN
6   Gokhan    Ankara   38       530      M   gokhan@x.com
8  Ibrahim    Berlin   41       400      M  ibrahim@x.com
9     Jale    Ankara   33       275      F     jale@x.com

In [32]:
# Combining conditions: use & (and), | (or), ~ (not)
# IMPORTANT: wrap each condition in parentheses!

# People older than 30 AND spending more than 300
high_value = df[(df["age"] > 30) & (df["spending"] > 300)]
print("High-value customers:")
print(f"\nHigh-value customers: {len(high_value)} rows")
print(high_value[["name", "age", "spending"]])
print()

# People from Berlin OR Ankara
not_istanbul = df[(df["city"] == "Berlin") | (df["city"] == "Ankara")]
print("Berlin or Ankara:")
print(f"\nBerlin or Ankara: {len(not_istanbul)} rows")
print(not_istanbul[["name", "city"]])

High-value customers:

High-value customers: 5 rows
      name  age  spending
1      Bea   34       450
3    Deniz   31       620
4     Elif   45       310
6   Gokhan   38       530
8  Ibrahim   41       400

Berlin or Ankara:

Berlin or Ankara: 7 rows
      name    city
0      Ali  Berlin
2      Can  Berlin
4     Elif  Ankara
5    Fatma  Berlin
6   Gokhan  Ankara
8  Ibrahim  Berlin
9     Jale  Ankara

In [28]:
# Shortcut: .isin() is cleaner than chaining multiple | conditions
istanbul_berlin = df[df["city"].isin(["Istanbul", "Berlin"])]
print(f"Istanbul or Berlin: {len(istanbul_berlin)} rows")

# Negate with ~ (tilde) = NOT
not_berlin = df[~(df["city"] == "Berlin")]
print(f"\nNot Berlin: {len(not_berlin)} rows")
print(not_berlin[["name", "city"]])

Istanbul or Berlin: 7 rows

Not Berlin: 6 rows
     name      city
1     Bea  Istanbul
3   Deniz  Istanbul
4    Elif    Ankara
6  Gokhan    Ankara
7    Hana  Istanbul
9    Jale    Ankara

In [36]:
# String filtering with .str accessor
# Names that start with a vowel (case-insensitive)
vowel_names = df[df["name"].str.lower().str[1].isin([ "l"])]
print("Names starting with a vowel:")
print(vowel_names["name"].tolist())

# Names containing "an"
has_an = df[df["name"].str.contains("an", case=False)]
print("\nNames containing 'an':")
print(has_an["name"].tolist())

Names starting with a vowel:
['Ali', 'Elif']

Names containing 'an':
['Can', 'Gokhan', 'Hana']

---
## 6. loc and iloc

These are the two main ways to select specific rows AND columns at the same time.

| | **loc** | **iloc** |
|---|---|---|
| **Selects by** | Labels (names) | Integer position |
| **End inclusive?** | Yes | No |
| **Syntax** | `df.loc[rows, cols]` | `df.iloc[rows, cols]` |

In [40]:
# loc: select by LABEL
# Rows 0 through 3 (INCLUSIVE), columns "name" and "city"
df.loc[0:3, ["name", "city"]]

    name      city
0    Ali    Berlin
1    Bea  Istanbul
2    Can    Berlin
3  Deniz  Istanbul

In [41]:
# iloc: select by POSITION (like Python list slicing)
# Rows at position 0, 1, 2 (NOT 3), columns at position 0 and 1
df.iloc[0:3, 0:2]

  name      city
0  Ali    Berlin
1  Bea  Istanbul
2  Can    Berlin

In [42]:
# THE BIG GOTCHA: loc includes the endpoint, iloc doesn't
# Both start at row 0 and go to "4"

loc_result = df.loc[0:4, "name"]    # 5 rows (0,1,2,3,4)
iloc_result = df.iloc[0:4, 0]        # 4 rows (0,1,2,3)

print(f"loc[0:4]  -> {len(loc_result)} rows: {loc_result.tolist()}")
print(f"iloc[0:4] -> {len(iloc_result)} rows: {iloc_result.tolist()}")

loc[0:4]  -> 5 rows: ['Ali', 'Bea', 'Can', 'Deniz', 'Elif']
iloc[0:4] -> 4 rows: ['Ali', 'Bea', 'Can', 'Deniz']

In [43]:
# loc with a boolean mask (very common pattern)
# "Give me the name and spending of people older than 30"
df.loc[df["age"] > 30, ["name", "spending"]]

      name  spending
1      Bea       450
3    Deniz       620
4     Elif       310
6   Gokhan       530
8  Ibrahim       400
9     Jale       275

In [45]:
# loc to MODIFY values (the safe way to assign)
df_copy = df.copy()

# Set spending to 999 for everyone in Berlin
df_copy.loc[df_copy["city"] == "Ankara", "spending"] = 999
print(df_copy[["name", "city", "spending"]])

      name      city  spending
0      Ali    Berlin       120
1      Bea  Istanbul       450
2      Can    Berlin        80
3    Deniz  Istanbul       620
4     Elif    Ankara       999
5    Fatma    Berlin       200
6   Gokhan    Ankara       999
7     Hana  Istanbul        90
8  Ibrahim    Berlin       400
9     Jale    Ankara       999

---
## 7. Groupby Basics

`groupby` splits your data into groups, applies a function to each group, and combines the results. It's like SQL's `GROUP BY`.

In [46]:
# Basic groupby: average spending per city
df.groupby("city")["spending"].mean()

city
Ankara      371.666667
Berlin      200.000000
Istanbul    386.666667
Name: spending, dtype: float64

In [47]:
# Multiple aggregations with .agg()
city_stats = df.groupby("city")["spending"].agg(["mean", "sum", "count", "min", "max"])
city_stats

                mean   sum  count  min  max
city
Ankara    371.666667  1115      3  275  530
Berlin    200.000000   800      4   80  400
Istanbul  386.666667  1160      3   90  620

In [49]:
# Different aggregations for different columns
multi_agg = df.groupby("city").agg(
    avg_age=("age", "mean"),
    total_spending=("spending", "sum"),
    num_customers=("name", "count")
)
multi_agg

            avg_age  total_spending  num_customers
city
Ankara    38.666667            1115              3
Berlin    30.000000             800              4
Istanbul  30.333333            1160              3

In [50]:
# Group by multiple columns
df.groupby(["city", "gender"])["spending"].mean()

city      gender
Ankara    F         292.5
          M         530.0
Berlin    F         200.0
          M         200.0
Istanbul  F         270.0
          M         620.0
Name: spending, dtype: float64

In [51]:
# What does the GroupBy object actually look like inside?
# .groups shows you which rows belong to which group
grouped = df.groupby("city")
print("Groups:", grouped.groups)
print()

# You can iterate over groups
for group_name, group_df in grouped:
    print(f"--- {group_name} ({len(group_df)} rows) ---")
    print(group_df[["name", "spending"]].to_string(index=False))
    print()

Groups: {'Ankara': [4, 6, 9], 'Berlin': [0, 2, 5, 8], 'Istanbul': [1, 3, 7]}

--- Ankara (3 rows) ---
  name  spending
  Elif       310
Gokhan       530
  Jale       275

--- Berlin (4 rows) ---
   name  spending
    Ali       120
    Can        80
  Fatma       200
Ibrahim       400

--- Istanbul (3 rows) ---
 name  spending
  Bea       450
Deniz       620
 Hana        90

---
## 8. Handling Missing Data (Quick Preview)

Our dataset has some `None` values in the email column. Here's how to detect and handle them.

In [52]:
# Check for missing values
print("Missing per column:")
print(df.isna().sum())
print(f"\nTotal missing: {df.isna().sum().sum()}")

Missing per column:
name        0
city        0
age         0
spending    0
gender      0
email       3
dtype: int64

Total missing: 3

In [53]:
# Filter rows WITH missing email
no_email = df[df["email"].isna()]
print("People without email:")
print(no_email[["name", "email"]])
print()

# Filter rows WITHOUT missing email
has_email = df[df["email"].notna()]
print(f"People with email: {len(has_email)}")

# WRONG WAY: never compare with == None or == NaN
# df[df["email"] == None]     # This works by accident, don't rely on it
# df[df["email"] == np.nan]   # This NEVER works (NaN != NaN)

People without email:
   name email
1   Bea   NaN
4  Elif   NaN
7  Hana   NaN

People with email: 7

---
## 9. Tricky Bits and Common Mistakes

Things that trip up beginners (and sometimes experienced people too).

In [61]:
# GOTCHA 1: Chained indexing creates a copy, not a view
# This might NOT change your original DataFrame
df_test = df.copy()
print(df_test)

# BAD: chained indexing
# df_test["spending"][0] = 9999  # SettingWithCopyWarning!

# GOOD: use loc
df_test.loc[9, "spending"] = 9999
print(f"Row 9 spending is now: {df_test.loc[9, 'spending']}")
print(df_test)

      name      city  age  spending gender          email
0      Ali    Berlin   28       120      M      ali@x.com
1      Bea  Istanbul   34       450      F            NaN
2      Can    Berlin   22        80      M      can@x.com
3    Deniz  Istanbul   31       620      M    deniz@x.com
4     Elif    Ankara   45       310      F            NaN
5    Fatma    Berlin   29       200      F    fatma@x.com
6   Gokhan    Ankara   38       530      M   gokhan@x.com
7     Hana  Istanbul   26        90      F            NaN
8  Ibrahim    Berlin   41       400      M  ibrahim@x.com
9     Jale    Ankara   33       275      F     jale@x.com
Row 9 spending is now: 9999
      name      city  age  spending gender          email
0      Ali    Berlin   28       120      M      ali@x.com
1      Bea  Istanbul   34       450      F            NaN
2      Can    Berlin   22        80      M      can@x.com
3    Deniz  Istanbul   31       620      M    deniz@x.com
4     Elif    Ankara   45       310      F            NaN
5    Fatma    Berlin   29       200      F    fatma@x.com
6   Gokhan    Ankara   38       530      M   gokhan@x.com
7     Hana  Istanbul   26        90      F            NaN
8  Ibrahim    Berlin   41       400      M  ibrahim@x.com
9     Jale    Ankara   33      9999      F     jale@x.com

In [62]:
# GOTCHA 2: df2 = df does NOT copy the data
df_a = pd.DataFrame({"x": [1, 2, 3]})
df_b = df_a           # SAME object, not a copy
df_c = df_a.copy()    # INDEPENDENT copy

df_b.loc[0, "x"] = 999

print(f"df_a[0] = {df_a.loc[0, 'x']}  (changed because df_b is the same object)")
print(f"df_c[0] = {df_c.loc[0, 'x']}  (unchanged because df_c is a copy)")

df_a[0] = 999  (changed because df_b is the same object)
df_c[0] = 1  (unchanged because df_c is a copy)

In [65]:
# GOTCHA 3: Forgetting parentheses in compound filters
# This FAILS, but the notebook keeps running because we catch any exception:
try:
    result = df[df["age"] > 30 & df["spending"] > 300]
    print("Wrong filter unexpectedly worked:")
except Exception as e:
    print(f"Error: {e}")
    print("Fix: wrap each condition in parentheses")
    print()

# This WORKS:
result = df[(df["age"] > 30) & (df["spending"] > 300)]
print("Correct result:")
print(result[["name", "age", "spending"]])

Error: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
Fix: wrap each condition in parentheses

Correct result:
      name  age  spending
1      Bea   34       450
3    Deniz   31       620
4     Elif   45       310
6   Gokhan   38       530
8  Ibrahim   41       400

In [67]:
# GOTCHA 4: groupby without aggregation gives you an object, not results
grouped = df.groupby("city")
print(type(grouped))  # DataFrameGroupBy, not a DataFrame!
print(grouped)        # Just shows the object, no data
print()

# You MUST call an aggregation
print("After .mean():")
print(grouped["spending"].mean())

<class 'pandas.api.typing.DataFrameGroupBy'>
<pandas.api.typing.DataFrameGroupBy object at 0x112a8c350>

After .mean():
city
Ankara      371.666667
Berlin      200.000000
Istanbul    386.666667
Name: spending, dtype: float64

In [68]:
# GOTCHA 5: read_csv guesses dtypes wrong sometimes
# Zip codes, IDs, phone numbers that start with 0 get read as integers
import io

csv_data = """name,zipcode
Ali,00123
Bea,10115"""

# BAD: pandas drops the leading zeros
df_bad = pd.read_csv(io.StringIO(csv_data))
print("Without dtype fix:")
print(df_bad)
print(f"  zipcode type: {df_bad['zipcode'].dtype}")
print()

# GOOD: force string type
df_good = pd.read_csv(io.StringIO(csv_data), dtype={"zipcode": str})
print("With dtype={'zipcode': str}:")
print(df_good)
print(f"  zipcode type: {df_good['zipcode'].dtype}")

Without dtype fix:
  name  zipcode
0  Ali      123
1  Bea    10115
  zipcode type: int64

With dtype={'zipcode': str}:
  name zipcode
0  Ali   00123
1  Bea   10115
  zipcode type: str

---
## 10. Trick Questions

Think about each one before revealing the answer.

<details>
<summary><strong>Q1:</strong> What does <code>df.loc[3:5]</code> return vs <code>df.iloc[3:5]</code>?</summary>

`loc[3:5]` returns rows with index labels 3, 4, and 5 (3 rows, both ends inclusive). `iloc[3:5]` returns rows at positions 3 and 4 (2 rows, end exclusive).
</details>

<details>
<summary><strong>Q2:</strong> You run <code>df[df["score"] != np.nan]</code> and get ALL rows back, even though some scores are missing. Why?</summary>

Any comparison with NaN returns False or True in unexpected ways. `NaN != NaN` is True, so every row passes the filter. Use `df[df["score"].notna()]` instead.
</details>

<details>
<summary><strong>Q3:</strong> You do <code>df2 = df</code> and then modify df2. Does df change too?</summary>

Yes! `df2 = df` makes both variables point to the same object. Use `df2 = df.copy()` to get an independent copy.
</details>

<details>
<summary><strong>Q4:</strong> Is <code>df["name"]</code> a DataFrame or a Series?</summary>

It's a Series. Single brackets with one column name always return a Series. Use `df[["name"]]` (double brackets) to get a DataFrame with one column.
</details>

<details>
<summary><strong>Q5:</strong> What happens if you call <code>df.groupby("city")</code> without an aggregation?</summary>

You get a DataFrameGroupBy object, not actual results. You must call `.mean()`, `.sum()`, `.agg()`, etc. to see numbers.
</details>

---
## 11. Exercises: Try It Yourself

Fill in the blanks and run each cell. The `assert` statements will tell you if you got it right.

In [73]:
# Exercise 1: How many rows are in df?
num_rows = df.shape[0] # YOUR CODE HERE (hint: use .shape)

assert num_rows == 10, f"Expected 10, got {num_rows}"
print(f"Correct! {num_rows} rows")

Correct! 10 rows

In [74]:
# Exercise 2: Get all people from Istanbul as a DataFrame
istanbul_people = df.loc[df["city"] == "Istanbul"]  # YOUR CODE HERE

assert len(istanbul_people) == 3, f"Expected 3 Istanbul people, got {len(istanbul_people)}"
assert list(istanbul_people["name"]) == ["Bea", "Deniz", "Hana"]
print("Correct! Istanbul people:", istanbul_people["name"].tolist())

Correct! Istanbul people: ['Bea', 'Deniz', 'Hana']

In [ ]:
# Exercise 3: Get the name and age of people with spending > 400
# Use loc with a boolean mask and column selection
high_spenders = ___  # YOUR CODE HERE

assert list(high_spenders.columns) == ["name", "age"], "Should have columns: name, age"
assert len(high_spenders) == 3, f"Expected 3 high spenders, got {len(high_spenders)}"
print("Correct!")
print(high_spenders)

In [75]:
# Exercise 4: Calculate the average age per city using groupby
avg_age_by_city = df.groupby("city")["age"].mean()  # YOUR CODE HERE

assert round(avg_age_by_city["Ankara"], 1) == 38.7, "Check your Ankara average"
assert round(avg_age_by_city["Berlin"], 1) == 30.0, "Check your Berlin average"
print("Correct!")
print(avg_age_by_city)

Correct!
city
Ankara      38.666667
Berlin      30.000000
Istanbul    30.333333
Name: age, dtype: float64

In [76]:
# Exercise 5: Count how many people have missing emails
missing_count = df.loc[df["email"].isnull()].shape[0]  # YOUR CODE HERE

assert missing_count == 3, f"Expected 3 missing emails, got {missing_count}"
print(f"Correct! {missing_count} people have no email")

Correct! 3 people have no email

In [77]:
# Exercise 6: Use iloc to get the last 3 rows and columns "name" and "spending"
# Hint: negative indexing works with iloc, and you need column positions
last_three = df.iloc[-3:, [0, 3]]  # YOUR CODE HERE

assert len(last_three) == 3, f"Expected 3 rows, got {len(last_three)}"
assert list(last_three.columns) == ["name", "spending"]
print("Correct!")
print(last_three)

Correct!
      name  spending
7     Hana        90
8  Ibrahim       400
9     Jale       275

In [80]:
df.groupby("city")["spending"].sum()

city
Ankara      1115
Berlin       800
Istanbul    1160
Name: spending, dtype: int64

In [82]:
# Exercise 7 (challenge): Find the city with the highest total spending
# Use groupby, sum, and idxmax
top_city = df.groupby("city")["spending"].sum().idxmax()  # YOUR CODE HERE

assert top_city == "Istanbul", f"Expected 'Istanbul', got '{top_city}'"
print(f"Correct! {top_city} has the highest total spending")

Correct! Istanbul has the highest total spending

---
## 12. Exercise Solutions

Only look after you've tried! Each solution is hidden.

<details>
<summary>Solution 1</summary>

```python
num_rows = df.shape[0]
```
</details>

<details>
<summary>Solution 2</summary>

```python
istanbul_people = df[df["city"] == "Istanbul"]
```
</details>

<details>
<summary>Solution 3</summary>

```python
high_spenders = df.loc[df["spending"] > 400, ["name", "age"]]
```
</details>

<details>
<summary>Solution 4</summary>

```python
avg_age_by_city = df.groupby("city")["age"].mean()
```
</details>

<details>
<summary>Solution 5</summary>

```python
missing_count = df["email"].isna().sum()
```
</details>

<details>
<summary>Solution 6</summary>

```python
last_three = df.iloc[-3:, [0, 3]]
# Or: df.iloc[-3:][ ["name", "spending"] ] but loc is cleaner:
# last_three = df.loc[df.index[-3:], ["name", "spending"]]
```
</details>

<details>
<summary>Solution 7</summary>

```python
top_city = df.groupby("city")["spending"].sum().idxmax()
```
</details>

---
## 13. Quick Reference Card

Run this cell to print a cheat sheet you can refer back to.

In [83]:
cheat_sheet = """
╔══════════════════════════════════════════════════════════════╗
║                  PANDAS ESSENTIALS CHEAT SHEET               ║
╠══════════════════════════════════════════════════════════════╣
║                                                              ║
║  LOAD DATA                                                   ║
║    pd.read_csv("file.csv")                                   ║
║    pd.read_csv("f.csv", dtype={"col": str}, nrows=100)       ║
║                                                              ║
║  INSPECT                                                     ║
║    df.head(), df.tail(), df.shape, df.dtypes                 ║
║    df.info(), df.describe(), df.columns                      ║
║                                                              ║
║  SELECT COLUMNS                                              ║
║    df["col"]           -> Series                             ║
║    df[["col"]]         -> DataFrame                          ║
║    df[["a", "b"]]      -> DataFrame with 2 cols              ║
║                                                              ║
║  FILTER ROWS                                                 ║
║    df[df["col"] > 5]                                         ║
║    df[(cond1) & (cond2)]    # AND                            ║
║    df[(cond1) | (cond2)]    # OR                             ║
║    df[~condition]            # NOT                           ║
║    df[df["col"].isin([a,b])]                                 ║
║                                                              ║
║  loc vs iloc                                                 ║
║    df.loc[rows, cols]   -> by LABEL, end INCLUSIVE            ║
║    df.iloc[rows, cols]  -> by POSITION, end EXCLUSIVE         ║
║                                                              ║
║  GROUPBY                                                     ║
║    df.groupby("col")["val"].mean()                           ║
║    df.groupby("col")["val"].agg(["mean","sum","count"])      ║
║    df.groupby("col").agg(new_name=("col","func"))            ║
║                                                              ║
║  MISSING DATA                                                ║
║    df.isna().sum()           # count missing per column      ║
║    df["col"].isna()          # boolean mask                  ║
║    df["col"].notna()         # opposite                      ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝
"""
print(cheat_sheet)

╔══════════════════════════════════════════════════════════════╗
║                  PANDAS ESSENTIALS CHEAT SHEET               ║
╠══════════════════════════════════════════════════════════════╣
║                                                              ║
║  LOAD DATA                                                   ║
║    pd.read_csv("file.csv")                                   ║
║    pd.read_csv("f.csv", dtype={"col": str}, nrows=100)       ║
║                                                              ║
║  INSPECT                                                     ║
║    df.head(), df.tail(), df.shape, df.dtypes                 ║
║    df.info(), df.describe(), df.columns                      ║
║                                                              ║
║  SELECT COLUMNS                                              ║
║    df["col"]           -> Series                             ║
║    df[["col"]]         -> DataFrame                          ║
║    df[["a", "b"]]      -> DataFrame with 2 cols              ║
║                                                              ║
║  FILTER ROWS                                                 ║
║    df[df["col"] > 5]                                         ║
║    df[(cond1) & (cond2)]    # AND                            ║
║    df[(cond1) | (cond2)]    # OR                             ║
║    df[~condition]            # NOT                           ║
║    df[df["col"].isin([a,b])]                                 ║
║                                                              ║
║  loc vs iloc                                                 ║
║    df.loc[rows, cols]   -> by LABEL, end INCLUSIVE            ║
║    df.iloc[rows, cols]  -> by POSITION, end EXCLUSIVE         ║
║                                                              ║
║  GROUPBY                                                     ║
║    df.groupby("col")["val"].mean()                           ║
║    df.groupby("col")["val"].agg(["mean","sum","count"])      ║
║    df.groupby("col").agg(new_name=("col","func"))            ║
║                                                              ║
║  MISSING DATA                                                ║
║    df.isna().sum()           # count missing per column      ║
║    df["col"].isna()          # boolean mask                  ║
║    df["col"].notna()         # opposite                      ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝

---
## Next up: Day 2 — Numpy Vectorization
Arrays, dtypes, vectorization, broadcasting, and the axis parameter.